version: '2'
services:
  factorio-master:
    build: ./build
    volumes:
      - ./volumes/master/sharedPlugins:/factorioClusterio/sharedPlugins
      - ./volumes/master/sharedMods:/factorioClusterio/sharedMods
      - ./volumes/master/database/:/factorioClusterio/database
      - ./volumes/master/config.json:/factorioClusterio/config.json
      - ./volumes/master/secret-api-token.txt:/factorioClusterio/secret-api-token.txt
    ports:
      - 8080:8080
    environment:
      - RCONPORT=34198
      - FACTORIOPORT=34197
      - MODE=master
    restart: always
  factorio-slave:
    build: ./build
    volumes:
      - ./volumes/slave/instances/:/factorioClusterio/instances/
      - ./volumes/slave/config.json:/factorioClusterio/config.json
      - ./volumes/slave/sharedMods:/factorioClusterio/sharedMods
      - ./volumes/slave/sharedPlugins:/factorioClusterio/sharedPlugins
    ports:
      - 34197:34197/udp
      - 34198:34198
    environment:
      - RCONPORT=34198
      - FACTORIOPORT=34197
      - MODE=client
      - INSTANCE=YOURINSTANCENAME
    depends_on:
      - factorio-master
    restart: always
